travis:
  secure:
    BINSTAR_TOKEN: jCnOvbGLul9Y8wGxwbwcPP5BygjGexkPtPc0XkwrilForMzJ3DykNUyVhEYaJhnFn8mYX16LL6v1AWiP6Z2dTuIF+ormswf19V4pZVzf1sdfDQOYdPqYhC5UqVXdhCkLpqj1ackQn/4Ndf0121rpbyVocwqpDhSQ29FU0KPBS9OKoDXqiSEW381+tbZrITYwMsyMg2+8bDJUpjORlevX44QyxPpP3/In3I183vf/0MHSfoUuBy3Vz6V3bOpEr7+FD1IOFhmmrnXBrmMKeJpYYLvotya/kBJuwvo3rPpmZbEO45TlTR5yoquYeBkzisOuuPMHwdDA75X8ZiBKU7uzUJ+WBDFANQczXNa2xuzn2sWAKNft4Y1+n9/U0YHyTS8hvo7SuX9ZpNDqyHEy++oBjN59h9XaaOQq6HiY1dTqLrfa8VuHmmzbnK0F0pAFYIrS7Cx9j7vTfng99rI8C3ngYm+8s0hF6fBmZQjOQGEUgntTSSdbk31A5GiHyE57uTPJLtYdVxCVfJF/DKgJRou0o3OrQyWFkAyyEfD45QVFAeW85A8e4VIrkMRVBAOrJQ1kFbgP6ReFvr0BDaXC3kOXhPdbih0CYn2S4bVhXXhG628VXU84YAga9nWIdksNciwLzQcEuWRfN+3a1wZw8ev56FWVkoXvoSLpcg/ibpC0GoQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
